name: Push to S3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{secrets.PUBLIC_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.PRIVATE_KEY}}
          AWS_REGION: 'ap-northeast-1'
      - name: Sync to S3
        run: aws s3 sync build s3://hitforfun.com --delete
