name: Push to S3

on: 
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.PUBLIC_KEY}}
          aws-secret-access-key: ${{secrets.PRIVATE_KEY}}
          aws-region: 'ap-northeast-1'
      - name: Build and push to S3
        run: npm install --prefix hit_website ; npm run build --prefix hit_website ; cd hit_website ; ls
