name: Push to S3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
        env:
          AWS_S3_BUCKET: hitforfun.com
          AWS_ACCESS_KEY_ID: ${{secrets.PUBLIC_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.PRIVATE_KEY}}
          AWS_REGION: 'ap-northeast-1'
          AWS_S3_ENDPOINT: "https://sts.ap-northeast-1.amazonaws.com"
