name: Push to S3

on: 
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.PUBLIC_KEY}}
          aws-secret-access-key: ${{secrets.PRIVATE_KEY}}
          aws-region: 'ap-northeast-1'
          
      - name: Sync to S3
        run: aws s3 sync ToS3 s3://hitforfun.com --delete
